### ISSUE TITLE
R-T3.4-2: The defect-prediction tool must display a GUI for the plugin (to be integrated in the IDE)

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-plugin#1]
ID | R-T3.4-2
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | USABILITY
User Story | As an Operations Engineer I want to use the tool with a Graphical User Interface
Requirement | The defect-prediction tool must display a GUI for the plugin (to be integrated in the IDE)
Extended Description | The tool should provide information about the state of the infrastructure (e.g. listing vulnerable nodes) in a graphical fashion.
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency | R-T2.3-3

**Comment by stefanodallapalma** [comment]
@gcasale  
This requirement is satisfied, see the [README](https://github.com/radon-h2020/radon-defect-prediction-plugin) for an overview of the GUI.

**Comment by gcasale** [comment]
Approved
