### ISSUE TITLE
R-T3.11 - Defect prediction automation

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/radon-defect-prediction-plugin#8]
| ID | R-T3.11 |
| --- | --- |
| Section | WP3: Methodology and Quality Assurance Requirements |
| Type | USABILITY |
| User Story |As a user I want to automate the defect prediction phase  |
| Extended Description | In order for automation, DPF needs to be scriptable. Either through an api or a CLI |
| Means of Verification | Unit tests |
| Dependency | N/A |

**Comment by stefanodallapalma** [comment]
@gcasale closing because redundant with #3

**Comment by gcasale** [comment]
Approved
